name: 기능 개선
title: '[improvement] '
description: 성능, 코드 품질, 사용자 경험 등의 개선 아이디어를 제안하세요
labels: ['improvement']
body:
  - type: textarea
    attributes:
      label: 어떤 부분을 개선하고 싶나요?
      placeholder: >
        개선이 필요한 문제나 불편한 점을 구체적으로 설명해주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 어떻게 개선하면 좋을까요?
      placeholder: >
        생각해둔 개선 방법이나 아이디어가 있다면 작성해주세요.
    validations:
      required: false
